# Generated by Django 5.2.14 on 2026-05-25 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Name')),
                ('email', models.EmailField(max_length=254, verbose_name='Email Address')),
                ('company', models.CharField(blank=True, max_length=255, null=True, verbose_name='Company Name')),
                ('service', models.CharField(max_length=100, verbose_name='Requested Service')),
                ('budget', models.CharField(max_length=100, verbose_name='Budget Range')),
                ('message', models.TextField(verbose_name='Project Details')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Submission Time')),
            ],
            options={
                'verbose_name': 'Contact Submission',
                'verbose_name_plural': 'Contact Submissions',
                'ordering': ['-created_at'],
            },
        ),
    ]
